name: release-app
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
    
      - run: yarn install
        working-directory: app
      - run: yarn build
        working-directory: app

      - name: Deploy
        run: aws s3 cp --recursive --region ap-northeast-2 build s3://ddat-hmm-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: app
